[package]
name = "auth-system"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.29", features = ["bundled"] }
argon2 = "0.5"
rpassword = "7.0"
rand_core = { version = "0.6", features = ["getrandom"] }